### ISSUE TITLE
[BUG] Some episodes on pantsubase.tv instantly downloads but I am not able to watch them

### ISSUE THREAD

**Issue by Melaquera73** [SuperMarcus/NineAnimator#258] opened 2021-05-24 12:32 UTC
**STOP!!** Before submitting this bug report, make sure you have filled out the information below and renamed the title of this issue (ex. `[BUG] UrlError when trying to stream an episode on 9ani.app`). The information you provide helps us diagnose the problem and organize our issue tracker.

**Describe the bug**
Replace this line with a clear and concise description of what the bug is.

**To Reproduce**
Replace this with the steps to reproduce the behavior:

**Expected behavior**
Replace this line with a clear and concise description of what you expected to happen.

**Screenshots**

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: iPad Air 2
 - OS: 14.4.2
 - Version: 1.2.7 Build 6

**Crash Log**
```
If applicable, paste the crash log inside this block.
(Goto Settings.app -> Privacy -> Analytics & Improvements -> Analytics Data to find crash logs)
```

**Additional context**

**Comment by uttiya10** [comment] 2021-05-25 20:54
Can you please say what anime and what episode you downloaded using pantsubase?
It would also be great if you can provide a screen recording of the issue!

**Comment by Melaquera73** [comment] 2021-05-26 18:40
I have noticed that it happened on quite a few so far but here is one :- Attack on Titan season 3 episode 12

**Comment by Melaquera73** [comment] 2021-05-26 18:41
https://user-images.githubusercontent.com/83816474/119714070-dba1c900-be7b-11eb-88fb-e706e8ea5273.MP4

**Comment by uttiya10** [comment] 2021-05-26 18:50
Thank you for the information. I see exactly why the episode is not being downloaded properly, and I'll fix the issue when I have time!

Technical root cause:
The source is incorrectly marking the video files as mp4, instead of m3u8 streams. 
This causes the app to use `URLSession` to download the episode, instead of `AVAssetDownloadURLSession`, resulting in a broken download.

**Comment by Melaquera73** [comment] 2021-05-26 19:36
Thank you very much!!

**Comment by uttiya10** [comment] 2021-05-27 00:35
Can you please try these steps:
1. Delete the broken download
2. Download and install this pre-release version of the app: https://github.com/uttiya10/NineAnimator/suites/2841095925/artifacts/63386188
3. Try downloading the episode again, and report if the issue is fixed

**Comment by Melaquera73** [comment] 2021-05-27 18:20
Thank you very much, It works now!

**Comment by Melaquera73** [comment] 2021-06-26 18:14
It doesn't work again.It either doesn't download at all or tells me to try other sources.

**Comment by uttiya10** [comment] 2021-06-26 19:07
May i know the anime and the episode number that you are trying to download?

**Comment by Melaquera73** [comment] 2021-06-27 12:18
None of the episodes from any anime I tried to download downloaded but here is the first one I found not downloading:

Monster Musume no Iru Nichijou episode 1

**Comment by Melaquera73** [comment] 2021-06-27 18:43
After I download the same episode from other sources it appears like this![image](https://user-images.githubusercontent.com/83816474/123555809-75bd9f80-d7a1-11eb-9f67-76f5c4c13278.png)

**Comment by Melaquera73** [comment] 2021-06-29 15:21
?

**Comment by Joseos123** [comment] 2021-07-02 05:01
please try the latest commit if you use xcode.

if you dont, im hoping someone will send the artifact link because i honestly dont know where it is haha.

ive had the same issues with you. its not just downloading but streaming as well, seems to be fixed with the latest commit

**Comment by Melaquera73** [comment] 2021-07-02 10:09
Haha,thanks!

**Comment by uttiya10** [comment] 2021-07-02 17:57
Sorry for the very late reply!
A bunch of the code base has been going through a internal restructuring, which is why it's taken some time for the sources to be fixed.

Here is where you can download the beta version of NineAnimator, which should have the sources fixed:
https://github.com/SuperMarcus/NineAnimator/actions/runs/992458342

**Comment by Melaquera73** [comment] 2021-07-02 18:18
It Ok,Thanks a Lot

**Comment by Melaquera73** [comment] 2021-07-03 11:08
It's Ok,Thanks a lot!

**Comment by Melaquera73** [comment] 2021-07-03 13:44
Some episodes are downloading and some aren't

Steins:Gate 0:

Episodes 1 and 2 are downloading but not 3 and when I try to stream episodes that aren't downloading this appears:![image](https://user-images.githubusercontent.com/83816474/124356277-9b79f700-dc2e-11eb-8885-7bc47d9bed69.png)

**Comment by Joseos123** [comment] 2021-07-03 14:39
i can confirm this problem too, but im pretty sure this is a completely new issue.

its a VERY VERY VERY VERY VERY common thing for a new bug to appear BECAUSE you fixed another so i wasnt that suprised.

just wait for the next major release because they are doing a lot of cool stuff in the background

doubt this will be fixed soon but it'll be cool if they do

**Comment by uttiya10** [comment] 2021-07-03 16:59
I can confirm this is NOT an issue with NineAnimator. The episode your trying to watch is simply not available on the website either, see the screenshot below.

Therefore, since this website doesn't have the episode you're looking for, I recommend using another source, like arrayanime.

![image](https://user-images.githubusercontent.com/56562649/124361463-65704f00-dbfd-11eb-90f3-592d326c0d7c.png)

**Comment by Melaquera73** [comment] 2021-07-03 18:22
Oh

**Comment by Awsomedude** [comment] 2021-07-03 18:39
> I can confirm this is NOT an issue with NineAnimator. The episode your trying to watch is simply not available on the website either, see the screenshot below.
> 
> Therefore, since this website doesn't have the episode you're looking for, I recommend using another source, like arrayanime.
> 
> ![image](https://user-images.githubusercontent.com/56562649/124361463-65704f00-dbfd-11eb-90f3-592d326c0d7c.png)

It does work if you change the server on the site, Pantsudrive to Gogo-Stream.

**Comment by uttiya10** [comment] 2021-07-03 18:42
If you would like to use gogo-stream, you can switch your source in NineAnimator to gogoanime

**Comment by uttiya10** [comment] 2021-07-03 18:44
> Oh,but I can download it from their site does that have nothing to do with this?

Their download link sends you to gogo's website. If you want to use gogoanime to download, follow the comment above^^

**Comment by Melaquera73** [comment] 2021-07-03 18:56
Ah,I see!

**Comment by Melaquera73** [comment] 2021-08-18 15:45
Cant download anything on any source

**Closed** 2021-09-18 06:08 UTC
Labels: bug
