### ISSUE TITLE
[BUG] Cannot build the app on Vscode

### ISSUE THREAD

**Issue by emmanuela0** [SuperMarcus/NineAnimator#326] opened 2022-08-24 04:44 UTC
### Steps to reproduce

<img width="1512" alt="Screen Shot 2022-08-24 at 00 16 44" src="https://user-images.githubusercontent.com/98354317/186330758-ffd72470-f13f-4dcf-8008-a86ccc1e83b8.png">

### Expected behavior

.

### Actual behavior

Build is failing and giving me multiple errors.

### NineAnimator version

1.2.7

### iOS version

iOS 15.6.1

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuperMarcus** [comment] 2022-08-24 13:07
Duplicate of #299

**Closed by SuperMarcus** 2022-08-24 13:07 UTC
Labels: duplicate

**Comment by emmanuela0** [comment] 2022-08-24 15:36
The problem was on my end, Xcode just needed an update.
