### ISSUE TITLE
[Feature Request] change the color of text

### ISSUE THREAD

**Issue by sovietanthem** [SuperMarcus/NineAnimator#70] opened 2020-03-24 07:08 UTC
I’m talking about changing the color of text to a color of our liking except for just purple.
This feature allows oled dark mode to work since the text wont look off and more customizability never hurts anyone.

**Comment by uttiya10** [comment] 2020-03-24 15:40
This is potentially a duplicate of #60

**Closed** 2020-03-24 22:10 UTC
Labels: duplicate, enhancement
