### ISSUE TITLE
I need authorization 

### ISSUE THREAD

**Issue by ash1120** [SuperMarcus/NineAnimator#134] opened 2020-06-08 04:32 UTC
I tried to subscribe to a show and it tells me I need authorization.
The app is NineAnimator

**Comment by uttiya10** [comment] 2020-06-08 04:37
This is not a bug, the authorization is most likely a captcha that you have to fill out. If you need help please check out our discord at: https://discord.gg/C4cHgZd

I will be closing this issue.

**Closed** 2020-06-08 13:55 UTC
