### ISSUE TITLE
Error issue

### ISSUE THREAD

**Issue by alex99c** [SuperMarcus/NineAnimator#59] opened 2020-02-28 00:34 UTC
I’m not sure what causes this issue but every time I try to click on an episode it gives those error. The error message is JSON could not be serialized because of error: the data couldn’t be read because it isn’t in the correct format.

**Comment by SuperMarcus** [comment] 2020-02-28 01:30
Duplicate of #58 or #55

**Closed by SuperMarcus** 2020-02-28 01:30 UTC
