### ISSUE TITLE
TestFlight NineAnimator has expired

### ISSUE THREAD

**Issue by eobi1976** [SuperMarcus/NineAnimator#191] opened 2020-11-05 21:52 UTC
So basically I was just wondering when the TestFlight version of NineAnimator will be available again on the AppStore because it has just expired

**Comment by uttiya10** [comment] 2020-11-05 21:55
This is a duplicate of issue #171 . Please read that issue to understand the situation.

**Closed by uttiya10** 2020-11-05 21:55 UTC
Labels: bug, duplicate
