### ISSUE TITLE
Sources Crashing, Not getting recognised & downloading issues

### ISSUE THREAD

**Issue by Thozhan-cell** [SuperMarcus/NineAnimator#179] opened 2020-09-12 13:57 UTC
Basically 9anime.ru is not working. I tried it for fugou keiji balance unlimited it would not load. When i tried downloading from animephae it had issues and would be stuck at queued. I also had issues with sound output when streaming from 4anime.to and other websites. There is constant crashing and i don t know what to do. I have tried deleting redownloading it doesnt seem to work.Oh yah there is also this like weird video for each time i access one of the websites with authentication.PLS HELP!
<img width="1548" alt="Screen Shot 2020-09-12 at 22 00 02 PM" src="https://user-images.githubusercontent.com/71181410/92997119-5ff92980-f543-11ea-9edb-3e7c777851df.png">
<img width="1548" alt="Screen Shot 2020-09-12 at 22 02 22 PM" src="https://user-images.githubusercontent.com/71181410/92997147-a77fb580-f543-11ea-9842-daa1511e30a3.png">

**Comment by uttiya10** [comment] 2020-09-13 22:55
Please fill out the form below so we can help you:
**To Reproduce**
Replace this with the steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
Replace this line with a clear and concise description of what you expected to happen.

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: [e.g. iPhone Xs Max]
 - OS: [e.g. iOS 13.3]
 - Version: [e.g. v1.2-3 or commit hash]
**Additional context**
Add any other context about the problem here.

**Comment by animudatte** [comment] 2020-10-10 10:49
the same thing is happening and im using macbook

**Comment by SuperMarcus** [comment] 2020-10-10 16:40
@animudatte which issue are you having? The source crashing? or downloading issues? or unable to authenticate? If you are having any one of these issues, please use the **Bug Report** template to [create a new issue](https://github.com/SuperMarcus/NineAnimator/issues/new/choose). When you're filling out bug reports, please read the text in the box and provide the requested information.

This issue (at the time) is invalid because @Thozhan-cell described multiple, unrelated issues, without providing the steps to reproduce any of these issues. As Uttiya replied in the previous comment, we need more than just the symptoms to diagnose and address any issues.

**Comment by SuperMarcus** [comment] 2020-10-10 16:45
Also, note that the macCatalyst builds are not very well tested, since they're built from our iOS codebase without any specialized modifications. There are still countless bugs that we need to fix and numerous optimizations that we can perform. Please continue to provide feedback and report bugs to us regarding the Catalyst builds.

**Comment by animudatte** [comment] 2020-10-11 05:54
well its with the 9anime source, i cant even look up the anime in the search section, far from even downloading

**Comment by uttiya10** [comment] 2020-10-11 19:29
Yes, the 9anime problem is a known issue. 9anime recently changed their entire website, therefore we need to update our code as well.

**Comment by SuperMarcus** [comment] 2020-10-12 16:47
Closing due to invalidity. If you are having any one of the described issues, please use the **Bug Report** template to [create a new issue](https://github.com/SuperMarcus/NineAnimator/issues/new/choose). When you're filling out bug reports, please read the text in the box and provide the requested information.

**Closed by SuperMarcus** 2020-10-12 16:47 UTC
Labels: invalid
